In [2]:
events = [
    {"name": "Valorant Champions 2025", "url": "https://www.vlr.gg/event/stats/2283/valorant-champions-2025"},
    {"name": "VCT 2025: Americas Stage 2", "url": "https://www.vlr.gg/event/stats/2501/vct-2025-americas-stage-2"},
    {"name": "VCT 2025: EMEA Stage 2", "url": "https://www.vlr.gg/event/stats/2498/vct-2025-emea-stage-2"},
    {"name": "VCT 2025: Pacific Stage 2", "url": "https://www.vlr.gg/event/stats/2500/vct-2025-pacific-stage-2"},
    {"name": "VCT 2025: China Stage 2", "url": "https://www.vlr.gg/event/stats/2499/vct-2025-china-stage-2"},
    {"name": "VCT 2025: Americas Stage 1", "url": "https://www.vlr.gg/event/stats/2347/vct-2025-americas-stage-1"},
    {"name": "VCT 2025: EMEA Stage 1", "url": "https://www.vlr.gg/event/stats/2380/vct-2025-emea-stage-1"},
    {"name": "VCT 2025: Pacific Stage 1", "url": "https://www.vlr.gg/event/stats/2379/vct-2025-pacific-stage-1"},
    {"name": "VCT 2025: China Stage 1", "url": "https://www.vlr.gg/event/2359/vct-2025-china-stage-1"},
    {"name": "Valorant Masters Toronto 2025", "url": "https://www.vlr.gg/event/stats/2282/valorant-masters-toronto-2025"},
    {"name": "Valorant Masters Bangkok 2025", "url": "https://www.vlr.gg/event/stats/2281/valorant-masters-bangkok-2025"},
    {"name": "VCT 2025: EMEA Kickoff", "url": "https://www.vlr.gg/event/stats/2276/vct-2025-emea-kickoff"},
    {"name": "VCT 2025: Americas Kickoff", "url": "https://www.vlr.gg/event/stats/2274/vct-2025-americas-kickoff"},
    {"name": "VCT 2025: Pacific Kickoff", "url": "https://www.vlr.gg/event/stats/2277/vct-2025-pacific-kickoff"},
    {"name": "VCT 2025: China Kickoff", "url": "https://www.vlr.gg/event/stats/2275/vct-2025-china-kickoff"}
]

In [3]:
pip install requests beautifulsoup4 pandas

Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: pandas in /Users/sagnik/Documents/Python/.venv/lib/python3.13/site-packages (3.0.1)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.4-cp313-cp313-macosx_10_13_universal2.whl.metadata (37 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/sagnik/Documents/Python/.venv/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sagnik/Documents/Python/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sagnik/Documents/Python/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.4-cp313-cp313-macosx_10_13_universal2.whl (208 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: urllib3, typing-extensions, soupsieve, idna, charset_normalizer, certifi, requests, beautifulsoup4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [beautifulsoup4]m [requests]
Successfully installed beautifulsoup4-4.14.3 certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 requests-2.32.5 soupsieve-2.8.3 typing-extensions-4.15.0 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

events = [
    {"name": "Valorant Champions 2025", "url": "https://www.vlr.gg/event/stats/2283/valorant-champions-2025"},
    {"name": "VCT 2025: Americas Stage 2", "url": "https://www.vlr.gg/event/stats/2501/vct-2025-americas-stage-2"},
    {"name": "VCT 2025: EMEA Stage 2", "url": "https://www.vlr.gg/event/stats/2498/vct-2025-emea-stage-2"},
    {"name": "VCT 2025: Pacific Stage 2", "url": "https://www.vlr.gg/event/stats/2500/vct-2025-pacific-stage-2"},
    {"name": "VCT 2025: China Stage 2", "url": "https://www.vlr.gg/event/stats/2499/vct-2025-china-stage-2"},
    {"name": "VCT 2025: Americas Stage 1", "url": "https://www.vlr.gg/event/stats/2347/vct-2025-americas-stage-1"},
    {"name": "VCT 2025: EMEA Stage 1", "url": "https://www.vlr.gg/event/stats/2380/vct-2025-emea-stage-1"},
    {"name": "VCT 2025: Pacific Stage 1", "url": "https://www.vlr.gg/event/stats/2379/vct-2025-pacific-stage-1"},
    {"name": "VCT 2025: China Stage 1", "url": "https://www.vlr.gg/event/2359/vct-2025-china-stage-1"},
    {"name": "Valorant Masters Toronto 2025", "url": "https://www.vlr.gg/event/stats/2282/valorant-masters-toronto-2025"},
    {"name": "Valorant Masters Bangkok 2025", "url": "https://www.vlr.gg/event/stats/2281/valorant-masters-bangkok-2025"},
    {"name": "VCT 2025: EMEA Kickoff", "url": "https://www.vlr.gg/event/stats/2276/vct-2025-emea-kickoff"},
    {"name": "VCT 2025: Americas Kickoff", "url": "https://www.vlr.gg/event/stats/2274/vct-2025-americas-kickoff"},
    {"name": "VCT 2025: Pacific Kickoff", "url": "https://www.vlr.gg/event/stats/2277/vct-2025-pacific-kickoff"},
    {"name": "VCT 2025: China Kickoff", "url": "https://www.vlr.gg/event/stats/2275/vct-2025-china-kickoff"}
]

def scrape_event_stats(event_name, url):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers)
    
    if response.status_code != 200:
        print(f"Failed to fetch {event_name}: {response.status_code}")
        return None
    
    soup = BeautifulSoup(response.content, "html.parser")
    table = soup.find("table")
    
    if not table:
        print(f"No table found for {event_name}")
        return None
    
    headers_row = table.find("thead").find_all("th")
    col_names = [th.text.strip() for th in headers_row]
    
    rows = []
    for tr in table.find("tbody").find_all("tr"):
        cells = tr.find_all("td")
        row = [td.text.strip() for td in cells]
        if row:
            rows.append(row)
    
    df = pd.DataFrame(rows, columns=col_names)
    df["event"] = event_name
    return df

all_data = []

for event in events:
    print(f"Scraping {event['name']}...")
    df = scrape_event_stats(event["name"], event["url"])
    if df is not None:
        all_data.append(df)
    time.sleep(3)

full_df = pd.concat(all_data, ignore_index=True)
full_df.to_csv("vlr_raw_stats.csv", index=False)
print("Done!", full_df.shape)

Scraping Valorant Champions 2025...
Scraping VCT 2025: Americas Stage 2...
Scraping VCT 2025: EMEA Stage 2...
Scraping VCT 2025: Pacific Stage 2...
Scraping VCT 2025: China Stage 2...
Scraping VCT 2025: Americas Stage 1...
Scraping VCT 2025: EMEA Stage 1...
Scraping VCT 2025: Pacific Stage 1...
Scraping VCT 2025: China Stage 1...
No table found for VCT 2025: China Stage 1
Scraping Valorant Masters Toronto 2025...
Scraping Valorant Masters Bangkok 2025...
Scraping VCT 2025: EMEA Kickoff...
Scraping VCT 2025: Americas Kickoff...
Scraping VCT 2025: Pacific Kickoff...
Scraping VCT 2025: China Kickoff...
Done! (877, 22)

In [5]:
print(full_df.shape)
print(full_df.columns.tolist())
full_df.head()

(877, 22)
['Player', 'Agents', 'Rnd', 'R2.0', 'ACS', 'K:D', 'KAST', 'ADR', 'KPR', 'APR', 'FKPR', 'FDPR', 'HS%', 'CL%', 'CL', 'KMax', 'K', 'D', 'A', 'FK', 'FD', 'event']

,Player,Agents,Rnd,R2.0,ACS,K:D,KAST,ADR,KPR,APR,...,HS%,CL%,CL,KMax,K,D,A,FK,FD,event
0,aspas\nMIBR,(+1),330,1.33,261.6,1.66,79%,164.7,0.97,0.13,...,26%,8%,2/26,32,319,192,44,67,23,Valorant Champions 2025
1,RieNs\nTH,,256,1.17,226.1,1.14,73%,148.9,0.79,0.33,...,34%,20%,7/35,23,203,178,85,18,12,Valorant Champions 2025
2,brawk\nNRG,,377,1.16,224.6,1.17,76%,144.7,0.73,0.34,...,17%,9%,4/47,28,275,236,128,26,23,Valorant Champions 2025
3,kaajak\nFNC,(+1),453,1.15,228.4,1.20,71%,148.2,0.82,0.20,...,32%,13%,4/30,30,372,311,90,95,59,Valorant Champions 2025
4,johnqt\nSEN,,126,1.14,187.0,1.13,79%,118.7,0.67,0.27,...,33%,9%,2/22,17,85,75,34,5,5,Valorant Champions 2025

In [6]:
print(full_df.columns.tolist())
full_df.head()

['Player', 'Agents', 'Rnd', 'R2.0', 'ACS', 'K:D', 'KAST', 'ADR', 'KPR', 'APR', 'FKPR', 'FDPR', 'HS%', 'CL%', 'CL', 'KMax', 'K', 'D', 'A', 'FK', 'FD', 'event']

,Player,Agents,Rnd,R2.0,ACS,K:D,KAST,ADR,KPR,APR,...,HS%,CL%,CL,KMax,K,D,A,FK,FD,event
0,aspas\nMIBR,(+1),330,1.33,261.6,1.66,79%,164.7,0.97,0.13,...,26%,8%,2/26,32,319,192,44,67,23,Valorant Champions 2025
1,RieNs\nTH,,256,1.17,226.1,1.14,73%,148.9,0.79,0.33,...,34%,20%,7/35,23,203,178,85,18,12,Valorant Champions 2025
2,brawk\nNRG,,377,1.16,224.6,1.17,76%,144.7,0.73,0.34,...,17%,9%,4/47,28,275,236,128,26,23,Valorant Champions 2025
3,kaajak\nFNC,(+1),453,1.15,228.4,1.20,71%,148.2,0.82,0.20,...,32%,13%,4/30,30,372,311,90,95,59,Valorant Champions 2025
4,johnqt\nSEN,,126,1.14,187.0,1.13,79%,118.7,0.67,0.27,...,33%,9%,2/22,17,85,75,34,5,5,Valorant Champions 2025

In [8]:
print(full_df.isnull().sum())
print("---")
print(full_df.dtypes)

Player    0
Agents    0
Rnd       0
R2.0      0
ACS       0
K:D       0
KAST      0
ADR       0
KPR       0
APR       0
FKPR      0
FDPR      0
HS%       0
CL%       0
CL        0
KMax      0
K         0
D         0
A         0
FK        0
FD        0
event     0
dtype: int64
---
Player    str
Agents    str
Rnd       str
R2.0      str
ACS       str
K:D       str
KAST      str
ADR       str
KPR       str
APR       str
FKPR      str
FDPR      str
HS%       str
CL%       str
CL        str
KMax      str
K         str
D         str
A         str
FK        str
FD        str
event     str
dtype: object

In [10]:
# step 1 - strip % signs first, before any numeric conversion
for col in ['KAST', 'HS%', 'CL%']:
    full_df[col] = full_df[col].str.replace('%', '').str.strip()

# step 2 - now convert all numeric columns including the cleaned % ones
numeric_cols = ['Rnd', 'R2.0', 'ACS', 'KAST', 'ADR', 'KPR', 'APR', 'FKPR', 'FDPR', 'HS%', 'CL%', 'KMax', 'K', 'D', 'A', 'FK', 'FD']

for col in numeric_cols:
    full_df[col] = pd.to_numeric(full_df[col], errors='coerce')

# step 3 - handle K:D ratio
full_df[['K_kd', 'D_kd']] = full_df['K:D'].str.split(':', expand=True)
full_df['KD_ratio'] = pd.to_numeric(full_df['K_kd'], errors='coerce') / pd.to_numeric(full_df['D_kd'], errors='coerce')
full_df = full_df.drop(columns=['K:D', 'K_kd', 'D_kd'])

# save
full_df.to_csv("vlr_clean_stats.csv", index=False)

print(full_df.dtypes)
print("---")
full_df.head()

AttributeError: Can only use .str accessor with string values, not floating

In [1]:
def get_playoff_match_urls(event_matches_url):
    """Scrape all match URLs from an event playoff page"""
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(event_matches_url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    
    match_links = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        # match URLs are /number/team1-vs-team2-...
        parts = href.strip("/").split("/")
        if len(parts) == 2 and parts[0].isdigit():
            full_url = "https://www.vlr.gg" + href
            if full_url not in match_links:
                match_links.append(full_url)
    
    return match_links

# test on Champions 2025 playoffs
urls = get_playoff_match_urls("https://www.vlr.gg/event/matches/2283/valorant-champions-2025/?series_id=5080")
print(f"Found {len(urls)} matches")
for u in urls:
    print(u)

NameError: name 'requests' is not defined

In [2]:
def get_playoff_match_urls(event_matches_url):
    """Scrape all match URLs from an event playoff page"""
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(event_matches_url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    
    match_links = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        # match URLs are /number/team1-vs-team2-...
        parts = href.strip("/").split("/")
        if len(parts) == 2 and parts[0].isdigit():
            full_url = "https://www.vlr.gg" + href
            if full_url not in match_links:
                match_links.append(full_url)
    
    return match_links

# test on Champions 2025 playoffs
urls = get_playoff_match_urls("https://www.vlr.gg/event/matches/2283/valorant-champions-2025/?series_id=5080")
print(f"Found {len(urls)} matches")
for u in urls:
    print(u)

NameError: name 'requests' is not defined

In [5]:
import requests
from bs4 import BeautifulSoup

def get_playoff_match_urls(event_matches_url):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(event_matches_url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    
    match_links = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        parts = href.strip("/").split("/")
        if len(parts) == 2 and parts[0].isdigit():
            full_url = "https://www.vlr.gg" + href
            if full_url not in match_links:
                match_links.append(full_url)
    
    return match_links

urls = get_playoff_match_urls("https://www.vlr.gg/event/matches/2283/valorant-champions-2025/?series_id=5080")
print(f"Found {len(urls)} matches")
for u in urls:
    print(u)

ModuleNotFoundError: No module named 'requests'

In [6]:
import requests
from bs4 import BeautifulSoup

def get_playoff_match_urls(event_matches_url):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(event_matches_url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    
    match_links = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        parts = href.strip("/").split("/")
        if len(parts) == 2 and parts[0].isdigit():
            full_url = "https://www.vlr.gg" + href
            if full_url not in match_links:
                match_links.append(full_url)
    
    return match_links

urls = get_playoff_match_urls("https://www.vlr.gg/event/matches/2283/valorant-champions-2025/?series_id=5080")
print(f"Found {len(urls)} matches")
for u in urls:
    print(u)

ModuleNotFoundError: No module named 'requests'

In [4]:
import subprocess
subprocess.run(["pip", "install", "requests", "beautifulsoup4"])

Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.12/site-packages (4.12.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests) (2024.12.14)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4) (2.5)

CompletedProcess(args=['pip', 'install', 'requests', 'beautifulsoup4'], returncode=0)

In [11]:
print(full_df.dtypes)

Player        str
Agents        str
Rnd         int64
R2.0      float64
ACS       float64
K:D           str
KAST      float64
ADR       float64
KPR       float64
APR       float64
FKPR      float64
FDPR      float64
HS%           str
CL%           str
CL            str
KMax        int64
K           int64
D           int64
A           int64
FK          int64
FD          int64
event         str
dtype: object

In [12]:
# strip % from HS% and CL%
full_df['HS%'] = full_df['HS%'].str.replace('%', '').str.strip()
full_df['CL%'] = full_df['CL%'].str.replace('%', '').str.strip()

# convert to numeric
full_df['HS%'] = pd.to_numeric(full_df['HS%'], errors='coerce')
full_df['CL%'] = pd.to_numeric(full_df['CL%'], errors='coerce')
full_df['CL'] = pd.to_numeric(full_df['CL'], errors='coerce')

# handle K:D ratio
full_df[['K_kd', 'D_kd']] = full_df['K:D'].str.split(':', expand=True)
full_df['KD_ratio'] = pd.to_numeric(full_df['K_kd'], errors='coerce') / pd.to_numeric(full_df['D_kd'], errors='coerce')
full_df = full_df.drop(columns=['K:D', 'K_kd', 'D_kd'])

# save
full_df.to_csv("vlr_clean_stats.csv", index=False)

print(full_df.dtypes)

ValueError: Columns must be same length as key

In [13]:
print(full_df['K:D'].head(10))

0    1.66
1    1.14
2    1.17
3    1.20
4    1.13
5    1.09
6    1.13
7    1.17
8    0.97
9    1.17
Name: K:D, dtype: str

In [14]:
full_df['KD_ratio'] = pd.to_numeric(full_df['K:D'], errors='coerce')
full_df = full_df.drop(columns=['K:D'])

full_df.to_csv("vlr_clean_stats.csv", index=False)

print(full_df.dtypes)

Player          str
Agents          str
Rnd           int64
R2.0        float64
ACS         float64
KAST        float64
ADR         float64
KPR         float64
APR         float64
FKPR        float64
FDPR        float64
HS%         float64
CL%         float64
CL          float64
KMax          int64
K             int64
D             int64
A             int64
FK            int64
FD            int64
event           str
KD_ratio    float64
dtype: object

In [15]:
full_df.describe()

,Rnd,R2.0,ACS,KAST,ADR,KPR,APR,FKPR,FDPR,HS%,CL%,CL,KMax,K,D,A,FK,FD,KD_ratio
count,877.000000,805.000000,867.000000,0.0,805.000000,877.000000,877.000000,805.000000,805.000000,805.000000,689.000000,0.0,877.000000,877.000000,877.000000,877.000000,877.000000,877.000000,877.000000
mean,281.140251,0.974658,193.128374,NaN,126.954907,0.678290,0.277754,0.098012,0.101602,28.657143,15.564586,NaN,22.892816,194.214367,194.404789,79.058153,26.594071,26.596351,0.974344
std,141.481850,0.130918,27.442565,NaN,16.610048,0.108157,0.096162,0.047917,0.043487,5.404459,7.605974,NaN,5.114882,107.419279,94.360968,50.636632,21.776403,19.324172,0.182506
min,20.000000,0.510000,118.000000,NaN,81.500000,0.300000,0.080000,0.000000,0.000000,13.000000,3.000000,NaN,6.000000,6.000000,9.000000,3.000000,0.000000,0.000000,0.400000
25%,170.000000,0.890000,174.000000,NaN,115.600000,0.610000,0.200000,0.060000,0.070000,25.000000,11.000000,NaN,20.000000,110.000000,121.000000,41.000000,11.000000,13.000000,0.860000
50%,261.000000,0.990000,192.500000,NaN,126.800000,0.680000,0.260000,0.080000,0.090000,28.000000,14.000000,NaN,23.000000,179.000000,187.000000,69.000000,22.000000,23.000000,0.980000
75%,378.000000,1.070000,211.450000,NaN,137.900000,0.750000,0.340000,0.120000,0.130000,32.000000,19.000000,NaN,26.000000,266.000000,257.000000,106.000000,36.000000,37.000000,1.080000
max,696.000000,1.370000,277.300000,NaN,173.600000,1.200000,0.640000,0.240000,0.250000,45.000000,100.000000,NaN,42.000000,579.000000,485.000000,345.000000,137.000000,111.000000,2.560000

In [16]:
# top 10 players by ACS across all events
top_acs = full_df[['Player', 'ACS', 'KD_ratio', 'ADR', 'HS%', 'event']].sort_values('ACS', ascending=False).head(10)
print(top_acs)

           Player    ACS  KD_ratio    ADR   HS%                          event
691     mada\nNRG  277.3      1.37  173.6  22.0     VCT 2025: Americas Kickoff
841   ZmjjKK\nEDG  270.4      1.27    NaN   NaN        VCT 2025: China Kickoff
329   lukxo\nLOUD  270.4      1.34  172.8  31.0     VCT 2025: Americas Stage 1
204     Meiy\nDFM  266.2      1.35  167.2  29.0      VCT 2025: Pacific Stage 2
690    penny\nFUR  266.0      1.68  165.9  24.0     VCT 2025: Americas Kickoff
265     stew\nJDG  262.4      1.22  169.1  36.0        VCT 2025: China Stage 2
0     aspas\nMIBR  261.6      1.66  164.7  26.0        Valorant Champions 2025
517  t3xture\nGEN  258.2      1.44  159.5  28.0  Valorant Masters Toronto 2025
520  Alfajer\nFNC  257.9      1.30  167.6  32.0  Valorant Masters Toronto 2025
589      nAts\nTL  257.6      1.32  155.1  26.0  Valorant Masters Bangkok 2025

In [17]:
# average performance per event (how different tournaments compare)
event_summary = full_df.groupby('event')[['ACS', 'KD_ratio', 'ADR', 'HS%']].mean().round(2)
print(event_summary)

                                  ACS  KD_ratio     ADR    HS%
event
VCT 2025: Americas Kickoff     195.26      0.99  128.14  27.43
VCT 2025: Americas Stage 1     194.64      0.98  128.70  27.69
VCT 2025: Americas Stage 2     193.07      0.98  126.42  27.41
VCT 2025: China Kickoff        194.73      0.96     NaN    NaN
VCT 2025: China Stage 2        193.71      0.97  127.85  29.18
VCT 2025: EMEA Kickoff         192.26      0.97  127.15  30.49
VCT 2025: EMEA Stage 1         193.09      0.98  127.24  30.24
VCT 2025: EMEA Stage 2         197.07      0.99  129.85  30.53
VCT 2025: Pacific Kickoff      193.44      0.98  126.83  28.21
VCT 2025: Pacific Stage 1      193.85      0.98  127.91  27.89
VCT 2025: Pacific Stage 2      194.06      0.98  126.71  28.90
Valorant Champions 2025        189.75      0.97  124.25  28.58
Valorant Masters Bangkok 2025  191.72      0.94  126.46  26.22
Valorant Masters Toronto 2025  187.48      0.96  123.40  29.07

In [18]:
full_df[['Player', 'Team']] = full_df['Player'].str.split('\n', expand=True)
print(full_df[['Player', 'Team']].head(10))

      Player  Team
0      aspas  MIBR
1      RieNs    TH
2      brawk   NRG
3     kaajak   FNC
4     johnqt   SEN
5     Smoggy   EDG
6       leaf    G2
7  something   PRX
8     Knight   BLG
9      skuba   NRG

In [19]:
full_df.to_csv("vlr_clean_stats.csv", index=False)

In [20]:
top_players = full_df[['Player', 'Team', 'ACS', 'KD_ratio', 'ADR', 'HS%', 'event']].sort_values('ACS', ascending=False).head(15)
print(top_players)

         Player  Team    ACS  KD_ratio    ADR   HS%  \
691        mada   NRG  277.3      1.37  173.6  22.0
841      ZmjjKK   EDG  270.4      1.27    NaN   NaN
329       lukxo  LOUD  270.4      1.34  172.8  31.0
204        Meiy   DFM  266.2      1.35  167.2  29.0
690       penny   FUR  266.0      1.68  165.9  24.0
265        stew   JDG  262.4      1.22  169.1  36.0
0         aspas  MIBR  261.6      1.66  164.7  26.0
517     t3xture   GEN  258.2      1.44  159.5  28.0
520     Alfajer   FNC  257.9      1.30  167.6  32.0
589        nAts    TL  257.6      1.32  155.1  26.0
756      Jemkin   RRQ  257.4      1.29  164.2  27.0
591       Derke   VIT  257.2      1.20  166.8  22.0
631  florescent   APK  256.6      1.16  172.9  38.0
81          OXY    C9  254.6      1.25  160.0  27.0
87         Sato   LEV  254.0      1.20  163.7  33.0

                             event
691     VCT 2025: Americas Kickoff
841        VCT 2025: China Kickoff
329     VCT 2025: Americas Stage 1
204      VCT 2025: Pacific Stage 2
690     VCT 2025: Americas Kickoff
265        VCT 2025: China Stage 2
0          Valorant Champions 2025
517  Valorant Masters Toronto 2025
520  Valorant Masters Toronto 2025
589  Valorant Masters Bangkok 2025
756      VCT 2025: Pacific Kickoff
591  Valorant Masters Bangkok 2025
631         VCT 2025: EMEA Kickoff
81      VCT 2025: Americas Stage 2
87      VCT 2025: Americas Stage 2

In [21]:
team_stats = full_df.groupby('Team')[['ACS', 'KD_ratio', 'ADR', 'HS%']].mean().round(2).sort_values('ACS', ascending=False)
print(team_stats)

          ACS  KD_ratio     ADR    HS%
Team
G2     204.44      1.09  132.64  24.23
PRX    202.84      1.06  133.75  27.23
NRG    199.82      1.03  130.35  23.95
EDG    199.44      1.02  128.14  28.06
BBL    198.91      1.01  130.50  28.27
GEN    198.83      1.08  129.20  29.14
FNC    198.52      1.06  132.12  29.88
FPX    198.25      1.02  128.42  30.80
VIT    198.16      1.00  128.70  27.57
TL     196.89      1.01  129.77  29.39
DRG    196.87      0.98  130.46  31.10
NS     196.31      1.02  127.01  26.20
KRÜ    196.15      1.02  128.79  25.13
DRX    196.11      1.03  128.73  28.04
TYL    195.71      0.96  132.66  29.80
100T   195.63      1.00  128.09  27.33
NOVA   195.51      0.96  122.07  25.67
LEV    195.15      0.99  129.58  30.00
C9     195.15      0.97  127.29  26.47
T1     194.88      0.97  127.71  28.56
FUT    194.73      0.94  127.21  28.73
KC     194.72      1.02  127.88  34.44
SEN    194.40      1.00  126.55  26.20
JDG    193.73      0.95  123.02  32.20
BME    193.26      0.96  125.59  24.20
NAVI   193.08      0.99  128.01  29.47
TH     192.31      0.96  126.31  33.68
EG     192.15      0.93  127.51  29.33
RRQ    191.52      0.98  125.80  30.36
TLN    191.49      0.99  125.07  31.93
XLG    191.16      0.95  124.59  33.00
LOUD   191.09      0.96  126.46  30.56
BLG    189.74      0.96  124.00  25.07
TEC    189.44      0.93  125.68  31.20
GX     188.87      0.93  125.03  31.09
MIBR   188.51      0.99  124.72  27.60
M8     188.44      0.95  125.15  32.60
ZETA   188.31      0.88  122.97  30.88
TE     187.77      0.90  116.21  27.00
DFM    187.48      0.91  123.50  29.53
GE     187.23      0.89  123.88  26.44
WOL    185.85      0.89  122.18  27.40
FUR    184.20      0.89  121.73  28.30
MKOI   184.11      0.88  122.77  28.00
TS     184.07      0.87  123.29  28.44
APK    183.29      0.86  122.06  29.25
2G     182.96      0.85  121.69  31.00
AG     174.16      0.83  129.84  28.40
Team      NaN      1.40     NaN    NaN
tarik     NaN      0.77     NaN    NaN

In [22]:
full_df['Region'] = full_df['event'].str.extract(r'(Americas|EMEA|Pacific|China|Masters|Champions)')
region_stats = full_df.groupby('Region')[['ACS', 'KD_ratio', 'ADR', 'HS%']].mean().round(2)
print(region_stats)

              ACS  KD_ratio     ADR    HS%
Region
Americas   194.34      0.98  127.77  27.51
Champions  189.75      0.97  124.25  28.58
China      194.21      0.97  127.85  29.18
EMEA       194.15      0.98  128.08  30.42
Masters    189.18      0.95  124.63  27.92
Pacific    193.79      0.98  127.17  28.33

In [23]:
full_df = full_df[~full_df['Team'].isin(['Team', 'tarik'])]
full_df.to_csv("vlr_clean_stats.csv", index=False)
print(f"Final row count: {len(full_df)}")

Final row count: 867

In [24]:
import os
print(os.getcwd())

/Users/sagnik/Documents/Python/BI prj

In [25]:
os.listdir(os.getcwd())

['main.ipynb', 'setup.py', 'vlr_raw_stats.csv', 'vlr_clean_stats.csv']

In [26]:
full_df['Region'] = full_df['event'].str.extract(r'(Americas|EMEA|Pacific|China|Masters|Champions)')
full_df[['Player', 'Team', 'ACS', 'KD_ratio', 'ADR', 'HS%', 'event', 'Region']].to_csv("tableau_players.csv", index=False)

full_df.groupby('Team')[['ACS', 'KD_ratio', 'ADR', 'HS%']].mean().round(2).reset_index().to_csv("tableau_teams.csv", index=False)

full_df.groupby('Region')[['ACS', 'KD_ratio', 'ADR', 'HS%']].mean().round(2).reset_index().to_csv("tableau_regions.csv", index=False)

print(os.listdir(os.getcwd()))

['main.ipynb', 'tableau_regions.csv', 'tableau_teams.csv', 'setup.py', 'vlr_raw_stats.csv', 'vlr_clean_stats.csv', 'tableau_players.csv']